### ISSUE TITLE
Please replace deprecated `set-output` command

### ISSUE THREAD

**Issue by PeterBurner** [philips-labs/list-folder-action#1]
## Description
GitHub deprecated the `set-output` command.
> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

Please replace the command with the new `$GITHUB_OUTPUT` syntax.

## References
 - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by PeterBurner** [comment]
Do you accept PRs?

**Comment by ScottGuymer** [comment]
Hi @PeterBurner thanks for the issue. This is now solved and released in https://github.com/philips-labs/list-folder-action/releases/tag/v2
